- src/lib.rs
> rename core::kinds::Sync to core::marker::Sync

- src/lib.rs
- `range(...)` was replaced by range syntax
- `Thread::spawn(...)` spawns a detached thread now (and has no `detach()` method anymore).
It still panics on my machine (with `thread '_1' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:144`) and throws an error about std being unstable, but the two changes should be alright...
> try to fix doc test

- src/lib.rs
- src/mutex.rs
- src/rw_lock.rs
Now there's no more temptation to publicize the fields!
> Use `const fn`s to avoid any need for a static lock types

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/mutex.rs
- src/once.rs
- src/rw_lock.rs
- src/util.rs
This also disabled `Once` when `const_fn` is not active as it doesn't seem to be useful without it (and there's no tests exercising it without static usage).
This shouldn't break anything as the default features are opt-in and should give the same behaviour as before.
> Allow disabling of asm, core_intrinsics and const_fn to build on stable

- src/mutex.rs
Replaces the CAS-loop locking the mutex with a loop trying one CAS and
then falling back on a read-only loop that spins until the lock
"looks unlocked" before trying CAS again.
This improves performance by reducing contention for the lock
cache line ("ping-ponging"). Unlike CAS, an atomic load does not
requires exclusive ownership of the cache line.
---
I did some benchmarking, using different number of threads trying to
increment an `u32` guarded by a `Mutex`. The timings are the time taken
for all threads to finish 10000 increments each. This was tested a quad-core
Intel i5 2500K.
Before:
```
test mutex_01 ... bench:     114,381 ns/iter (+/- 13,282) = 87 MB/s
test mutex_02 ... bench:     961,716 ns/iter (+/- 203,341) = 20 MB/s
test mutex_04 ... bench:   3,400,672 ns/iter (+/- 695,725) = …
```
> Improve Mutex performance

- src/once.rs
While looking at the implementation of `Once`, I saw this oddity. I figured it couldn't possibly be right. The comment mentions it has the same bounds as RwLock, which has Send + Sync. I suppose it's a typo?
> Wrong Sync + Sync bound in Once

- src/lib.rs
`const_unsafe_cell_new` and `const_atomic_usize_new` are stable now and don't need to be enabled by feature.
> Fix compile error on nightly-2018-08-14

- Cargo.toml
- src/once.rs
Added Once constant initialization via constant. This allows `Once` to be used on stable Rust with constant initialization.
> added Once constant initialization via constant

- src/once.rs
- src/rw_lock.rs
Adds some useful Debug implementations for Once, RwLockReadGuard and RwLockWriteGuard.
Maybe this project should have `#![deny(missing_debug_impl)]` ?
> Add missing Derive(Debug)

- src/mutex.rs
- src/once.rs
- src/rw_lock.rs
Displaying a lock with {:x?} or {:#?} propagates desired formatting to the locked data.
> Debug keeps formatting

- Cargo.toml
- README.md
- src/lib.rs
- src/mutex.rs
- src/once.rs
- src/rw_lock.rs
Given the recent merge to stable of `const_fn`, a feature flag is no longer necessary.
> Remove need for const_fn feature

- Cargo.toml
- README.md
Is it OK to bump the version given recent release of Rust 2018? I'd like to make use of this crate in a `stable` environment.
> Prepare for a 0.5.0 release?

- src/mutex.rs
- src/rw_lock.rs
warning: use of deprecated item 'core::sync::atomic::ATOMIC_USIZE_INIT': the new function is now preferred
> Remove deprecated ATOMIC_USIZE_INIT and ATOMIC_BOOL_INIT

- src/rw_lock.rs
Fixes #65.
I fully expect there to be some issues with this, so I'm going to get a few more eyes to look over it.
I've done a very quick performance test with the parking lot benchmarks:
```
$ cargo run --bin rwlock --release 1 3 100 10000 10 5
spin::RwLock (new)   - [write]     43.180 kHz [read]    129.347 kHz
spin::RwLock (old)   - [write]     43.146 kHz [read]    129.297 kHz
```
I genuinely have no idea whether those arguments make for a good test lol. Happy to rerun with something else.
Also not sure how you want to handle semver here.
> Rewrite RwLock to use folly upgradeable implementation

- src/mutex.rs
- src/rw_lock.rs
When holding a `&mut` to a lock, you statically know from the type checker that you hold the only reference to the lock at that time, and that no guard exists.
You can therefor by-pass the locking and access the wrapped data directly.
This commit simply copy-pastes `std::sync::Mutex::get_mut` and `std::sync::RwLock::get_mut` implementations, removing poisons.
> Add get_mut to Mutex and RwLock

- src/once.rs
Avoids the extra memory requirements and wrapping from an Option around
the stored type. This also completes a TODO by making it obsolete.
> Switch Once to MaybeUninit

- src/mutex.rs
- src/rw_lock.rs
These impls are safe for spinlocks because they operate outside the global threading model.
> Added Send + Sync impls for guards and reader/writer counts

- src/mutex.rs
- src/rw_lock.rs
I wasn't thinking through my past changes properly. This PR removed those guard trait impls that are unsound.
> Removed unsound guard Sync impls

- src/lazy.rs
- src/lib.rs
The implementation is copied from the `SyncLazy` implementation in the standard library.
Resolves #88.
> Add a `Lazy` type as alternative to `std::sync::Lazy`

- src/barrier.rs
- src/lib.rs
closes #28 
I'm not sure if there is interest in this, but I saw the issue and wanted to give it a shot. The implementation borrows heavily from the standard library, so I left their copyright notice in. I'm not sure of the proper mechanism for handling that. 
The examples still use stdlib, but I can write up other examples if there is interest in merging this. 
Also, I suspect there might be a more performant way to pull this off, so I'd appreciate feedback there. 
Thanks!
> barrier implementation

- README.md
Spin is licensed under MIT, but the README states that it's
licensed under Apache 2.0. Update the README to be consistent with
LICENSE.
> Fix license inconsistency

- CHANGELOG.md
- src/once.rs
When Once goes out of scope, contained value will be leaked, since MaybeUninit requires manual dropping.
This patch implements Drop for Once and drops the value if it was previously initialized.
> Once: Don't leak internal value when Once goes out of scope

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/debug.rs
- src/barrier.rs
- src/lazy.rs
- src/lib.rs
- src/mutex.rs
- src/mutex/spin.rs
- src/mutex/ticket.rs
- src/once.rs
- src/relax.rs
- src/rw_lock.rs
This currently has issues due to https://github.com/rust-lang/rust/issues/50822. Event fairly mundane examples will not compile because the compiler does not infer the default parameter without a type annotation, and type namespace paths are not type annotations.
The following example...
```rust
let mylock = spin::Mutex::new(0);
```
...fails with...
```
error[E0282]: type annotations needed for `spin::Mutex<i32, R>`
--> test.rs:1:14
|
1 | let mylock = spin::Mutex::new(0);
|     ------   ^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `R`
|     |
|     consider giving `mylock` the explicit type `spin::Mutex<i32, R>`, where the type parameter `R` is specified
error: aborting due to previous error
```
I'm undecided about what approach to use to solve this. Perhaps we should use a …
> Added relax strategy parameter

- src/lazy.rs
- src/mutex/spin.rs
- src/mutex/ticket.rs
- src/once.rs
- src/rwlock.rs
Even if it is possible to store a both reference to the lock and the pointer to the inner data, from a leaked guard, in some wrapped struct, this requires storing two words, which is suboptimal, when the inner data is literally just a field inside the lock struct. And while it is possible to use `lock_api`'s guard types with spin as the underlying lock, where `lock_api` has `data_ptr`, it would be really useful if `spin` could also directly do this.
> Allow getting the inner pointer directly for locks.

- src/once.rs
On most architectures, even strongly-ordered x86_64, `SeqCst` is slower than Acquire-Release, and in many situations not even required. This PR replaces SeqCst with Acquire-Release, just like the orderings used in `Once` from libstd.
The only thing I am unsure about, is whether `Relaxed` would suffice when indicating that there been a panic, but given the `RwLock` vulnerability related to `Relaxed` in the past, I think it's best to stick to `Release`. Panics are not supposed to be optimized anyway.
> Use Acquire-Release rather than SeqCst in Once.

- CHANGELOG.md
- src/once.rs
This also removes the `panicked` field from the panic unwind guard in call_once, cf. https://github.com/mvdnes/spin-rs/issues/110. Hence, the destructor will _only_ be called when unwinding after a panic, and otherwise it will become a no-op no matter how stupid the compiler may be (without optimizations, that is).
The major benefit of using enums instead of raw constants, is that we don't need to put `_ => unreachable_unchecked!()` at the end of all match statements, and therefore adding new enum variants will not silently cause UB if one would forget to add the new variants there.
> Use enums and u8 instead of usize in Once.

- src/once.rs
This PR adds a method `try_call_once` to `Once`, which uses a fallible initializer. This is similar to [`once_cell::sync::OnceCell::get_or_try_init`](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html#method.get_or_try_init).
> Add `Once::try_call_once`

- Cargo.toml
- README.md
- src/lib.rs
- src/mutex/spin.rs
- src/mutex/ticket.rs
- src/once.rs
- src/rwlock.rs
Add optional `portable_atomic` feature to enable the `portable-atomic` crate for use of emulated atomic operations on platforms that don't have them. 
This is in response to https://github.com/mvdnes/spin-rs/issues/114. Code changes follow closely those of previously proposed `atomic-polyfill` PR https://github.com/mvdnes/spin-rs/pull/115
I've expanded a bit on the feature and its implications in the README.
Tested as working with my app (unpublished yet) - a host USB stack on Atmel SAM D21 which has a single Cortex-M0 core. 
I will gladly update this PR if any changes are deemed necessary.
> Add portable_atomic feature

- Cargo.toml
- README.md
- The default feature of portable-atomic is mainly for users who use atomics larger than the pointer width or use older compilers; AFAIK, it is not necessary for spin-rs' use case, and disabling it may improve compile times slightly.
- It is only cfg 'portable_atomic_**unsafe**_assume_single_core' is unsafe. It is safe to enable the portable_atomic feature itself.
> Disable default features of portable-atomic, and fix docs about portable_atomic feature

- src/once.rs
Without this change, one of these two test methods fails about .75% of
the time (3 times in 500 runs). With this change, all tests pass in
5000 out of 5000 runs, so flaky failures should be a thing of the
past. I tried to reason a way to use a mutex or something here to
avoid fusing the methods, but I couldn't reason out a way to make it
work gracefully so I took the easy way out.
> once: merge two tests to prevent flaky test failures

- src/mutex/spin.rs
Allows tests to run under `-Zmiri-retag-fields` without issues. Main thing is replacing the mutable reference with a pointer, because otherwise a new lock is allowed to succeed technically before the drop glue for the previous one finishes, which miri reports as invalid.
> Fix stacked-borrows for SpinMutex

- .github/workflows/rust.yml
This PR adds some more tests to the CI, including:
- Tests to make sure it runs on `no_std` environments.
- Build with all features enabled and disabled.
- Run MIRI to make sure no unsound behavior is occurring.
> Add more tests to the CI

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- src/relax.rs
- src/rwlock.rs
As far as I know, there is no official Minimum Safe Rust Version (MSRV) policy for this crate, which makes it difficult to include it in crates that do have an MSRV policy. After some testing and adjustment, I've found that the MSRV for this crate is **1.38.0**. If you disable some features, it's probably lower, but I think a two-year old version of Rustc is conservative enough. This pull request adds an MSRV policy, as well as a test in the CI to make sure that the crate builds on the MSRV.
> Add an MSRV policy

- Cargo.toml
- README.md
The main change in this release is adding an optional `critical-section` feature[^1] to support custom critical section implementations with [rust-embedded's critical-section](https://github.com/rust-embedded/critical-section) crate. (https://github.com/taiki-e/portable-atomic/pull/51) This allows `portable-atomic` to provide atomic CAS on multicore systems that do not have native atomic CAS instructions.
`portable-atomic` is not used in `spin`'s public API and the (cfg) interfaces of `portable-atomic` 0.3 and `portable-atomic` 1.x are compatible, so this update should not be a breaking change. (https://github.com/taiki-e/portable-atomic/issues/61#issue-1530014746)
[^1]: This is a feature, not a cfg; `critical-section` 1.x doesn't provide the default or opt-in potentially unsound …
> Update portable-atomic to 1

- src/rwlock.rs
This PR restores the following auto trait implementations that have been unintentionally(?) removed in #136.
- [`RwLockWriteGuard<'_, T, R>: Send`](https://docs.rs/spin/0.9.4/spin/rwlock/struct.RwLockWriteGuard.html#impl-Send-for-RwLockWriteGuard%3C%27a%2C%20T%2C%20R%3E) if `T: Send + Sync`
- [`RwLockWriteGuard<'_, T, R>: Sync`](https://docs.rs/spin/0.9.4/spin/rwlock/struct.RwLockWriteGuard.html#impl-Sync-for-RwLockWriteGuard%3C%27a%2C%20T%2C%20R%3E) if `T: Send + Sync`
- [`RwLockReadGuard<'_, T>: Send`](https://docs.rs/spin/0.9.4/spin/rwlock/struct.RwLockReadGuard.html#impl-Send-for-RwLockReadGuard%3C%27a%2C%20T%3E) if `T: Sync`
- [`RwLockReadGuard<'_, T>: Sync`](https://docs.rs/spin/0.9.4/spin/rwlock/struct.RwLockReadGuard.html#impl-Sync-for-RwLockReadGuard%3C%27a%2C%20T%3E) if `T: …
> Bring back the `Send` and `Sync` implementations for `RwLock{Read,Write,Upgradable}Guard`

- src/mutex/fair.rs
This PR adds the following auto trait implementations so that it's in line with other `MutexGuard` types.
- `FairMutexGuard<'_, T>: Send` if `T: Send`
- `FairMutexGuard<'_, T>: Sync` if `T: Sync`
> Implement `Send` and `Sync` for `FairMutexGuard`

- src/mutex/spin.rs
This PR restores the following auto trait implementations that have been unintentionally removed in #125.
- [`SpinMutexGuard<'_, T>: Send`](https://docs.rs/spin/0.9.4/spin/mutex/spin/struct.SpinMutexGuard.html#impl-Send-for-SpinMutexGuard%3C%27a%2C%20T%3E) if `T: Send`
- [`SpinMutexGuard<'_, T>: Sync`](https://docs.rs/spin/0.9.4/spin/mutex/spin/struct.SpinMutexGuard.html#impl-Sync-for-SpinMutexGuard%3C%27a%2C%20T%3E) if `T: Sync`
- [`MutexGuard<'_, T>: Send`](https://docs.rs/spin/0.9.4/spin/mutex/struct.MutexGuard.html#impl-Send-for-MutexGuard%3C%27a%2C%20T%3E) if `T: Send` and `!cfg!(feature = "use_ticket_mutex")`
- [`MutexGuard<'_, T>: Sync`](https://docs.rs/spin/0.9.4/spin/mutex/struct.MutexGuard.html#impl-Sync-for-MutexGuard%3C%27a%2C%20T%3E) if `T: Sync` and `!cfg!(feature = …
> Bring back the `Send` and `Sync` implementations for `SpinMutexGuard`

- src/once.rs
This PR fixes issue #148 by retrying if the called-once function returns an error while another thread is also attempting to call a function.
> Fix #148 (UB in `try_call_once`)

- src/mutex/spin.rs
- src/rwlock.rs
Hi,
I'm working on implementing sync primitives in [Theseus OS](https://github.com/theseus-os/Theseus) on top of spin locks. We currently [have to implement our own spin lock](https://github.com/theseus-os/Theseus/blob/cb77432051dde0caf7fcf7eb4c04fa231916f624/libs/sync/src/mutex.rs#L146-L281) that is identical to `spin` except that it exposes `try_lock_weak`, so that we can have custom `lock` implementations that use a weak CMPXCHG, while still using a strong CMPXCHG for `try_lock`.
It would be nice if we could upstream this so that we could directly depend on `spin`. I think it makes sense to include it as `spin` is often used to build higher-level primitives which could use a weak CMPXCHG for better performance.
> Expose weak versions of CAS methods

- .github/workflows/rust.yml
- Cargo.toml
- src/lib.rs
This provides a better error message if the end user forgets to use the cfg or feature. (Also allows using the critical-section feature instead of the cfg.)
```console
$ cargo build --target thumbv6m-none-eabi --no-default-features --features spin_mutex,portable_atomic
Compiling portable-atomic v1.3.2
error: dependents require atomic CAS but not available on this target by default;
consider using portable_atomic_unsafe_assume_single_core cfg or critical-section feature.
see <https://docs.rs/portable-atomic/latest/portable_atomic/#optional-cfg> for more.
```
This also reverts the following commits (partially):
- https://github.com/mvdnes/spin-rs/commit/94cd9c54d717e9db854dc00e5683d9749b1d8cb2
- https://github.com/mvdnes/spin-rs/commit/b1ee8150f292be95fec166b141029d1e6af983f2
- …
> Enable portable-atomic's require-cas feature

- src/mutex.rs
Fixes some broken type links in the [mutex module](https://docs.rs/spin/latest/spin/mutex/index.html).
Ty!
> Fix some broken doc links

- src/mutex/spin.rs
- src/mutex/ticket.rs
- src/rwlock.rs
Adds a missing space in the Debug implementations for RwLock and spin and ticket mutexes
> Fix Debug formatting

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
Fixes #170 - non-breaking feature update - based on & supersedes PR #171
__UPDATED as follows__
- include `dep:` syntax updates from PR #171
- update some documentation to update reference & avoid duplicated info
- increase MSRV to 1.60 in Cargo.toml & in `.github/`
- crate version -> 0.10.0
I have also tried CI in my own fork: https://github.com/brody4hire/spin-rs/pull/1
---
P.S. I was hoping that the implicit feature support would be removed in Rust 2024, which is part of the root cause, but this update is now held up: https://github.com/rust-lang/cargo/issues/12826#issuecomment-2386352960
---
/cc @jamesmunns @Dirbaio
> more intuitive portable-atomic feature etc.

- src/rwlock.rs
Changes:
- Rename old feature name`lock_api1` to new feature name `lock_api` (I guess this has been forgotten?).
- Should import `lock_api_crate` as the package name instead of external `lock_api` crate dependency.
- Associated type of phantom data of RwLock requires that it already implement the RelaxStrategy trait.
> Fix lock_api feature name for RawRwLockUpgradeDowngrade

- src/lib.rs
This API allows writing more convenient internal fileds of a structure conversion!
> Add lock_api mapped read/write guard for RwLock
